### PR TITLE
MARP-555: add system prompt for edit feature

### PR DESCRIPTION
**Pull request by linhpd-axonivy**

### CODE REVIEW

**Review by ivy-rew — APPROVED** [review]
looks promising; does it also work with the 'ask'/explain tasks? or do we have any draw back there?

since we have no test against a live infrastructure, it would be cool to share a recorded GIF, proofing that this prompt works on a real-world project, using all kinds of the assistent methods ... just like I did https://github.com/axonivy-market/openai-connector/issues/11#issuecomment-1564315624 ... I'd file this onto the issue itself.
... with it, we have it easier to drive future changes and understand the previously available functionality.

**Comment by linhpd-axonivy** [comment]
I think this PR will only fix the edit feature. I tested some cases, and they worked, but I'm not 100% sure. The result depends on the user prompt, and sometimes it doesn't meet our expectations.

**Comment by ivy-rew** [comment]
> I think this PR will only fix the edit feature. I tested some cases, and they worked, but I'm not 100% sure. The result depends on the user prompt, and sometimes it doesn't meet our expectations.

We should check though, that for instance the 'ask' mode still works ... as it provided good results. IF it doesn't, it seem like the wrong location to add the 'chat-gpt' system hint ... then we may rather should do it per action; not globally for all requests.

**Comment by linhpd-axonivy** [comment]
I prepared new GIF for edit feature
edit

**Comment by ivy-rew** [comment]
> I prepared new GIF for insert feature edit [ edit ](https://private-user-images.githubusercontent.com/138570547/352987257-f9a16c3d-b44c-47c4-b5a5-4899f20730ea.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNDYzMTUsIm5iZiI6MTcyMjI0NjAxNSwicGF0aCI6Ii8xMzg1NzA1NDcvMzUyOTg3MjU3LWY5YTE2YzNkLWI0NGMtNDdjNC1iNWE1LTQ4OTlmMjA3MzBlYS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQwOTQwMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYWIxZjNkMzg2YTJkNmYwY2E5MzlmYWYzMTkwM2EzNDg4Mzc5OTk3MTQ4NDkzYTZmYTdjYmZiMTExMzFlNTA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eQDhJh6meXSE5-olYv4NZAUjMD10Ahud0DuzUnn4A3M) [ ](https://private-user-images.githubusercontent.com/138570547/352987257-f9a16c3d-b44c-47c4-b5a5-4899f20730ea.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNDYzMTUsIm5iZiI6MTcyMjI0NjAxNSwicGF0aCI6Ii8xMzg1NzA1NDcvMzUyOTg3MjU3LWY5YTE2YzNkLWI0NGMtNDdjNC1iNWE1LTQ4OTlmMjA3MzBlYS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQwOTQwMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYWIxZjNkMzg2YTJkNmYwY2E5MzlmYWYzMTkwM2EzNDg4Mzc5OTk3MTQ4NDkzYTZmYTdjYmZiMTExMzFlNTA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eQDhJh6meXSE5-olYv4NZAUjMD10Ahud0DuzUnn4A3M)

insert looks great; please update the tests to reflect the new input/output behavior:
https://github.com/axonivy-market/openai-connector/blob/master/openai-connector-test/src/com/axonivy/connector/openai/mock/json/assist-insert.json
https://github.com/axonivy-market/openai-connector/blob/master/openai-connector-test/src/com/axonivy/connector/openai/mock/json/assist-insert-response.json

**Review by ivy-rew — CHANGES_REQUESTED** [review]
good, always think about test ... also on removal of features; I think there are mock-services for this that we no longer need?

**Review by ivy-rew — APPROVED** [review]

**Review by ndkhanh-axonivy — APPROVED** [review]
LGTM

**Comment by linhpd-axonivy** [comment]
Hi @ivy-rew ,
Can you help me take a look at the failed tests? They run fine on my local machine.

**Comment by ivy-rew** [comment]
> Hi @ivy-rew , Can you help me take a look at the failed tests? They run fine on my local machine.

@phhung-axonivy knows what to do -> `@IvyTest(enableWebServer=true)`

**Pull request merged**
